 //!Actions type


export const types={
     RENDER:"RENDER",
     ADD_TODO:"ADD_TODO",
     TOOGLE_TODO:"TOOGLE_TODO",
     DELETE_TODO:"DELETE_TODO",
     LOGIN:"LOGIN",
     SET_VISIBILITY_FILTER:"SET_VISIBILITY_FILTER"
} 